/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.unidad1.vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * Ventana Registro
 * @author jorge canche, luis martinez, eliezer couoh
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Monto = new javax.swing.JLabel();
        CuentaD = new javax.swing.JLabel();
        CuentaO = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        Mon = new javax.swing.JTextField();
        CD = new javax.swing.JTextField();
        CO = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO");

        Nombre.setText("Nombre completo:");

        Monto.setText("Monto:");

        CuentaD.setText("Cuenta destino:");

        CuentaO.setText("Cuenta origen:");

        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });

        Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonActionPerformed(evt);
            }
        });

        Registrar.setText("Registrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(Monto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mon, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CuentaD)
                            .addComponent(CuentaO))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CD, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(CO))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Registrar)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monto)
                    .addComponent(Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaD)
                    .addComponent(CD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuentaO)
                    .addComponent(CO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Registrar)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonActionPerformed

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CD;
    private javax.swing.JTextField CO;
    private javax.swing.JLabel CuentaD;
    private javax.swing.JLabel CuentaO;
    private javax.swing.JTextField Mon;
    private javax.swing.JLabel Monto;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter
     * @return Metodo que retorna del TextField la cuenta del empleado
     */
    public JTextField getCD() {
        return CD;
    }

    /**
     * Setter
     * @param CD : Es la cuenta a la que se le deposita al empleado.
     */
    public void setCD(JTextField CD) {
        this.CD = CD;
    }

    /**
     * Getter
     * @return Metodo que regresa del TextField la cuenta del empleado.
     */
    public JTextField getCO() {
        return CO;
    }

    /**
     * Setter
     * @param CO : Es la cuenta de la empresa, de la cual se hace el deposito.
     */
    public void setCO(JTextField CO) {
        this.CO = CO;
    }

    /**
     * Getter
     * @return Metodo que retorna del TextField la cuenta del empleado
     */
    public JLabel getCuentaD() {
        return CuentaD;
    }

    /**
     * Setter
     * @param CuentaD : Es la cuenta a la que se le deposita al empleado.
     */
    public void setCuentaD(JLabel CuentaD) {
        this.CuentaD = CuentaD;
    }

    /**
     * Getter
     * @return Metodo que regresa del JLabel del TextField la cuenta del empleado.
     */
    public JLabel getCuentaO() {
        return CuentaO;
    }

    /**
     * Setter
     * @param CuentaO : Es la cuenta de la empresa, de la cual se hace el deposito.
     */
    public void setCuentaO(JLabel CuentaO) {
        this.CuentaO = CuentaO;
    }

    /**
     * Getter
     * @return Metodo que regresa del TextField la cantidad que se le deposito al empleado
     */
    public JTextField getMon() {
        return Mon;
    }

    /**
     * Setter
     * @param Mon : Es la cantidad de dinero que se le deposita al empleado.
     */
    public void setMon(JTextField Mon) {
        this.Mon = Mon;
    }

    /**
     * Getter
     * @return Metodo que regresa del JLabel la cantidad que se le deposito al empleado
     */
    public JLabel getMonto() {
        return Monto;
    }

    /**
     * Setter
     * @param Monto : Es la cantidad de dinero que se pone en el Jlabel para que se le deposita al empleado.
     */
    public void setMonto(JLabel Monto) {
        this.Monto = Monto;
    }

    /**
     * Getter
     * @return Metodo que regresa del JTextField el Nombre.
     */
    public JTextField getNom() {
        return Nom;
    }

    /**
     * Setter
     * @param Nom: Metodo que define el Nombre.
     */
    public void setNom(JTextField Nom) {
        this.Nom = Nom;
    }

    /**
     * Getter
     * @return Metodo que regresa del JLabel del JTextField el Nombre.
     */
    public JLabel getNombre() {
        return Nombre;
    }

    /**
     * Setter
     * @param Nombre: Metodo que define en el JLabel, el Nombre.
     */
    public void setNombre(JLabel Nombre) {
        this.Nombre = Nombre;
    }

    /**
     * Getter
     * @return Retorna el registro echo y pone los datos en el archivo CSV.
     */
    public JButton getRegistrar() {
        return Registrar;
    }

    /**
     * Setter
     * @param Registrar: Registra al empleado y los datos los pone en el archivo CSV.
     */
    public void setRegistrar(JButton Registrar) {
        this.Registrar = Registrar;
    }


    public JLabel getjLabel1() {
        return jLabel1;
    }


    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
}
